# Site settings
title:       "Andrey Danilov"
header_title: "Andrey Danilov Page"
email:       your@ema.il
author:      Andrey Danilov
description: "My page"
baseurl:     ""
url:         "https://evilpencil.github.io/"
date_format: "%-d.%m.%Y"

# Social icons
github_username: EvilPencil

# Yandex_Metrika
Yandex_Metrika:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/:title/"
paginate:     15
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]
