# Site settings
title:       "Andrey Danilov"
header_title: "Andrey Danilov Page"
email:       your@ema.il
author:      Andrey Danilov
description: "My page"
baseurl:     ""
url:         "https://evilpencil.github.io/"
date_format: "%-d.%m.%Y"
