# Site settings
title: "Home Page"
github_username: EvilPencil


collections:
  authors:
    output: true
  pages:
    output: true
    permalink: "/:name"

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year/:i_month/:i_day/:title"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Conversion
markdown: kramdown
highlighter: rouge

paginate: 10
paginate_path: "/blog/page/:num"
